### ISSUE TITLE
CheckedStorage Crash

### ISSUE THREAD

**Issue by WenXin20** [kreezxil/Lava-Dynamics#20]
Minecraft v1.12.2
Forge v14.23.5.2838
Lava Dynamics v5.6.2

I got this crash while near a volcano, something to do with CheckedStorage.
[Crash Report](https://paste.dimdev.org/litazukocu.mccrash)

**Comment by eleksploded** [comment]
Can you open up your world file and send me the file called LD_CheckedStorage along with the log leading to this crash?

**Comment by WenXin20** [comment]
Changed to .txt to upload it:
[LD_CheckedStorage.txt](https://github.com/kreezxil/Lava-Dynamics/files/3453043/LD_CheckedStorage.txt)

Log: 
https://gist.github.com/WenXin20/fa216e69b2f2345b4859a26acacbfc61

**Comment by eleksploded** [comment]
Ok, so... This is a problem of the mod was not able to write the your save folder, as windows/java/something denied the mods access to the file system. Try running minecraft with admin privileges and see if that fixes the problem

**Comment by WenXin20** [comment]
How would I do that? I should be the admin on my laptop account already, I'm the only one who uses it.

**Comment by eleksploded** [comment]
You should just right click the launcher and say run as admin

**Comment by WenXin20** [comment]
Ok thanks, I should be able to try it out again tonight or tomorrow.

**Comment by WenXin20** [comment]
If I'm using the Twitch launcher, would right-clicking and then clicking on "run as administrator" work too?

**Comment by eleksploded** [comment]
I think so

**Comment by WenXin20** [comment]
Just tried v5.6.5, and almost immediately going into my test world it crashes the same way. But after creating a new test world, that one worked fine.
Though didn't try running it with admin privileges yet.

**Comment by eleksploded** [comment]
So maybe that test world has some file privilege problems. Weird.

**Comment by WenXin20** [comment]
I thought the same thing.

**Comment by WenXin20** [comment]
I got a similar [crash](https://paste.dimdev.org/inobuhalim.mccrash) with v5.6.6, but with the newer test world. Access is being denied again for some reason. But it does seem to be working most of the time.
```
[23:04:22] [Server thread/INFO]: [com.eleksploded.lavadynamics.storage.VolcanoStorage:save:79]: java.io.IOException: Access is denied
[23:04:22] [Server thread/INFO]: [com.eleksploded.lavadynamics.storage.VolcanoStorage:save:79]: 	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
[23:04:22] [Server thread/INFO]: [com.eleksploded.lavadynamics.storage.VolcanoStorage:save:79]: 	at java.io.File.createNewFile(File.java:1012)
[23:04:22] [Server thread/INFO]: [com.eleksploded.lavadynamics.storage.VolcanoStorage:save:79]: 	at com.eleksploded.lavadynamics.storage.VolcanoStorage.save(VolcanoStorage.java:74)
[23:04:22] [Server thread/INFO]: [com.eleksploded.lavadynamics.storage.VolcanoStorage:save:79]: 	at com.eleksploded.lavadynamics.storage.StorageManager.save(StorageManager.java:56)
[23:04:22] [Server thread/INFO]: [com.eleksploded.lavadynamics.storage.VolcanoStorage:save:79]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1366_StorageManager_save_Save.invoke(.dynamic)
[23:04:22] [Server thread/INFO]: [com.eleksploded.lavadynamics.storage.VolcanoStorage:save:79]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[23:04:22] [Server thread/INFO]: [com.eleksploded.lavadynamics.storage.VolcanoStorage:save:79]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[23:04:22] [Server thread/INFO]: [com.eleksploded.lavadynamics.storage.VolcanoStorage:save:79]: 	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1008)
[23:04:22] [Server thread/INFO]: [com.eleksploded.lavadynamics.storage.VolcanoStorage:save:79]: 	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408)
[23:04:22] [Server thread/INFO]: [com.eleksploded.lavadynamics.storage.VolcanoStorage:save:79]: 	at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:337)
[23:04:22] [Server thread/INFO]: [com.eleksploded.lavadynamics.storage.VolcanoStorage:save:79]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:691)
[23:04:22] [Server thread/INFO]: [com.eleksploded.lavadynamics.storage.VolcanoStorage:save:79]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
[23:04:22] [Server thread/INFO]: [com.eleksploded.lavadynamics.storage.VolcanoStorage:save:79]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[23:04:22] [Server thread/INFO]: [com.eleksploded.lavadynamics.storage.VolcanoStorage:save:79]: 	at java.lang.Thread.run(Thread.java:745)
```
Edit: It seems like once this happens, then it starts crashing repeatedly once I reenter the world after a couple of minutes.

**Comment by eleksploded** [comment]
Can you run the compatibility helper from the GitHub release section and launch one of those crashing worlds, then send me the log?

**Comment by WenXin20** [comment]
Sorry it took so long to get back to this. I tried last night to replicate the crash with the same world, but it didn't happen. 
I'll post here again if I can get it to happen again.
